### ISSUE TITLE
Why controller.config and controller.configAnnotations are map of maps?

### ISSUE THREAD

**Issue by sorjef** [pulumi/pulumi-kubernetes-ingress-nginx#22]
### What happened?

The creation of the resource with the valid `controller.config` results in an error.

### Steps to reproduce

Here is a part of the original config in Yaml format:

```yaml
  nginx-ctrl:
    type: kubernetes-ingress-nginx:IngressController
    properties:
      controller:
        config:
          http-snippet: |
            proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=15m use_temp_path=off;
            proxy_cache_key $scheme$proxy_host$request_uri;
            proxy_cache_lock on;
            proxy_cache_use_stale updating;
```

### Expected Behavior

Helm chart with a valid ConfigMap should be deployed successfully.

### Actual Behavior

```sh
Diagnostics:
  pulumi:pulumi:Stack (infra-root):
    error: kubernetes-ingress-nginx:index:Controller is not assignable from {config: {http-snippet: string}}
    
      on Pulumi.yaml line 154:
     154:       controller:
    
    Cannot assign '{config: {http-snippet: string}}' to 'kubernetes-ingress-nginx:index:Controller':
      config: Cannot assign '{http-snippet: string}' to 'Map<Map<string>>':
        http-snippet: Cannot assign type 'string' to type 'Map<string>'
```

### Output of `pulumi about`

CLI          
Version      3.39.1
Go Version   go1.19
Go Compiler  gc

Plugins
NAME                      VERSION
azure-native              unknown
kubernetes                unknown
kubernetes-ingress-nginx  unknown
yaml                      unknown

Host     
OS       darwin
Version  12.5
Arch     x86_64

This project is written in yaml

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
